In [ ]:
import random
import numpy as np

In [ ]:
class GridWorld():
    def __init__(self):
        self.x=0
        self.y=0
    
    def step(self, a):
        if a==0:
            self.move_left()
        elif a==1:
            self.move_up()
        elif a==2:
            self.move_right()
        elif a==3:
            self.move_down()

        reward = -1  
        done = self.is_done()
        return (self.x, self.y), reward, done

    def move_left(self):
        if self.y==0:
            pass
        elif self.y==3 and self.x in [0,1,2]:
            pass
        elif self.y==5 and self.x in [2,3,4]:
            pass
        else:
            self.y -= 1

    def move_right(self):
        if self.y==1 and self.x in [0,1,2]:
            pass
        elif self.y==3 and self.x in [2,3,4]:
            pass
        elif self.y==6:
            pass
        else:
            self.y += 1
      
    def move_up(self):
        if self.x==0:
            pass
        elif self.x==3 and self.y==2:
            pass
        else:
            self.x -= 1

    def move_down(self):
        if self.x==4:
            pass
        elif self.x==1 and self.y==4:
            pass
        else:
            self.x+=1

    def is_done(self):
        if self.x==4 and self.y==6:
            return True
        else:
            return False
      
    def reset(self):
        self.x = 0
        self.y = 0
        return (self.x, self.y)

In [ ]:
class QAgent():

  def __init__(self):
    self.q_table = np.zeros(shape=(5, 7, 4))
    self.eps = 0.9
    self.gamma = 1
    
  def select_action(self, s):
    x, y = s
    coin = random.random()
    if coin < self.eps:
      return random.randint(0, 3)
    else:
      action_val = self.q_table[x, y, :]
      action = np.argmax(action_val)
    
    return action

  def update_table(self, transition): # transition을 받음
    s, a, r, s_prime = transition # state transition
    x, y = s # 현재 state
    next_x, next_y = s_prime # next_state
    a_prime = self.select_action(s_prime) # action of next_state
    self.q_table[x,y,a] = self.q_table[x,y,a] + 0.1*(r + self.gamma * self.q_table[next_x,next_y,a_prime] - self.q_table[x,y,a]) # 업데이트
  
  def anneal_eps(self):
    self.eps -= 0.03
    self.eps = max(self.eps, 0.1)

  def show_table(self):
    q_lst = self.q_table.tolist()
    data = np.zeros((5,7))
    for row_idx in range(len(q_lst)):
        row = q_lst[row_idx]
        for col_idx in range(len(row)):
            col = row[col_idx]
            action = np.argmax(col)
            data[row_idx, col_idx] = action
    print(data)

In [ ]:
def main():
  env = GridWorld()
  agent = QAgent()
  epi = 1000

  for n in range(epi): # episode
    done = False

    s = env.reset()
    while not done: # 에이전트 경험 쌓기
      a = agent.select_action(s) # 해당 state에서 action
      s_prime, r, done = env.step(a) # next_state, reward, 종료 여부 반환
      agent.update_table((s, a, r, s_prime)) # 업데이트
      s = s_prime
    agent.anneal_eps()

  agent.show_table()

In [ ]:
main()

[[3. 3. 0. 3. 3. 2. 3.]
 [3. 3. 0. 2. 2. 3. 3.]
 [2. 3. 0. 1. 0. 3. 3.]
 [2. 2. 2. 1. 0. 3. 3.]
 [0. 2. 1. 1. 0. 2. 0.]]
